### ISSUE TITLE
How to get that shit Tokenrubish?

### ISSUE THREAD

**Issue by bobybobybob** [jalmeroth/ESP8266-OAUTH2#1]
I seek and seek and find that token rubish not on google api website.

**Comment by bobybobybob** [comment]
What Google Rubbish is need to get it work?  It offer me Google.AI, Google Identity Toolkit , TokenServiceAPI, GMAIL-API and and and

**Comment by jalmeroth** [comment]
Come back, when you have learned how to ask questions on the internet.

**Comment by bobybobybob** [comment]
Hahaha
I will never come back and look for bether solution with good documentation.
