### ISSUE TITLE
certificate doesn't match

### ISSUE THREAD

**Issue by GajeraDeep** [jalmeroth/ESP8266-OAUTH2#2]
every time I try to upload the code it throws the same sentence, I'm using oath for firebase related stuff. Do I need to make changes to fingerprint ?? If yes how..?

And what are fingerprint used for ..?

**Comment by jalmeroth** [comment]
I haven't used it for Firebase, so I don't know, but you can try the latest version (4b0c5e0be43a51eb9f426ecf018b0a504db34f98), which verifies the certificate and not the fingerprint.
