### ISSUE TITLE
Fingerprint changes

### ISSUE THREAD

**Issue by Brandon2255p** [jalmeroth/ESP8266-OAUTH2#3]
I had a similar implementation of google oauth to get a token for other api services. The issue I has was that the fingerprint changes every so often (couple weeks?). Have you seen this happening?
Your verify statement should fail then.

**Comment by jalmeroth** [comment]
This should work, if you verify the certificate chain. See my latest commit 4b0c5e0be43a51eb9f426ecf018b0a504db34f98.

**Comment by Brandon2255p** [comment]
I'll give it a try thanks for the efforts
